### ISSUE TITLE
Sign In Botton on first setup leads to 404 error on the website

### ISSUE THREAD

**Issue by NetanelH2** [earlyai/earlyai-vscode-release#11]
**Describe the bug**
Trying to sign in to the plugin as a user but encounter 404 Error.

**To Reproduce**
1. Install the extension.
2. Click on Sign In.
3. Click on Sign In button.

**Expected behavior**
Should open a page to sign in with/register.

**Screenshots**
![Screenshot 2024-12-12 at 14 41 01](https://github.com/user-attachments/assets/cbd5562b-9d7e-437b-bf5c-5408ec25bc5b)

**Additional context**
URL: http://auth.startearly.ai/?vscodeVariant=stable

**Comment by liorf1** [comment]
Hi Netanel,

Thank you for reporting this issue and providing detailed steps to reproduce it.

It seems there was a temporary glitch with our authentication service that may have caused the 404 error you encountered. The issue should now be resolved.

Could you please try signing in again and let us know if the problem persists? If you still encounter the issue, any additional details (e.g., screenshots or logs) would be helpful for further troubleshooting.

We sincerely apologize for the inconvenience and appreciate your patience and understanding.

Best regards,
EarlyAI Team

**Comment by ksjitendra** [comment]
I have installed an extension, but I can't find the singing button.

**Comment by liorf1** [comment]
> I have installed an extension, but I can't find the singing button.

Hi @ksjitendra,

We just launched our documentation site.
Checkout the following guide at [signing-in](https://docs.startearly.ai/docs/GettingStarted/sign-in).

Tell us if you are facing further issues.

EarlyAI Team

**Comment by NetanelH2** [comment]
> Hi Netanel,
> 
> 
> 
> Thank you for reporting this issue and providing detailed steps to reproduce it.
> 
> 
> 
> It seems there was a temporary glitch with our authentication service that may have caused the 404 error you encountered. The issue should now be resolved.
> 
> 
> 
> Could you please try signing in again and let us know if the problem persists? If you still encounter the issue, any additional details (e.g., screenshots or logs) would be helpful for further troubleshooting.
> 
> 
> 
> We sincerely apologize for the inconvenience and appreciate your patience and understanding.
> 
> 
> 
> Best regards,
> 
> EarlyAI Team

Issue fixed
Thanks
