### ISSUE TITLE
Incorrect markdown anchor link in setup-and-configuration-guide.md

### ISSUE THREAD

**Issue by lorenzojkrl** [earlyai/earlyai-vscode-release#5]
**Describe the bug**
In setup-and-configuration-guide.md, [troubleshooting section](#6troubleshooting) should be [troubleshooting section](#5troubleshooting) to point to the correct section.

**To Reproduce**
1. Go to https://www.startearly.ai/docs/setup-and-configuration-guide#3preparingtousetheextension
2. Click on 'to the errors in the [troubleshooting section](https://www.startearly.ai/docs/setup-and-configuration-guide#6troubleshooting).'
3. You will notice nothing happens because the anchor link points to 6troubleshooting

**Expected behavior**
Should scroll to section 5. Troubleshooting

**Comment by sharonyb** [comment]
Resolved.
Also update the documentation to reflect the JavaScript support.

Thank you.
