### ISSUE TITLE
it does not detect Date.now() usage while generating the test suite

### ISSUE THREAD

**Issue by ViktorMasnyi** [earlyai/earlyai-vscode-release#8]
**Describe the bug**
I have a Nest JS module with one service attached to it. This is the service method example snippet:
`public async updateSomething() {
        const timestamp = Date.now();
        // some code that uses timestamp
}
`
the problem is that the generated test does not have the mock implementation of the Date.now() like this:
`describe('happy Path', () => {
        beforeAll(() => {
            jest.spyOn(Date, 'now').mockImplementation(() => 1_726_637_240_024);
        });
        afterAll(() => {
            (Date.now as jest.Mock).mockRestore();
        });
        it(test something) {
        }
`

**To Reproduce**
Steps to reproduce the behaviour:
1. try to generate test for some function that uses Date.now() call

**Expected behaviour**
it should add Date.now() mock implementation to beforeAll hook within the test generated

**Comment by sharonyb** [comment]
Hi Viktor,
Thank you for bringing that issue to our attention. 
We identify it and working on a fix.
